version: '3.7'
services:
  mysql_dev:
    image: mysql:8.0.3
    container_name: mysql_dev
    command: mysqld --user=root --verbose
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "file_management_db"
      MYSQL_USER: "file_user"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - file_management_dev_net
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_dev
    links:
      - mysql_dev:file_management_dev_db
    networks:
      - file_management_dev_net
networks:
  file_management_dev_net:
    driver: bridge